### ISSUE TITLE
Support for capistrano-rvm

### ISSUE THREAD

**Issue by codebycliff** [juicyparts/capistrano-rpush#5]
I want to start off by saying I'm not positive the issue is with this gem, but I thought I would start here. 

We are adding push notification support to our application using `rpush`. We added `capistrano-rpush` so we can start the daemon on deploy. This is currently failing because it can't find the `bundle` command (see red arrow below). I believe this is because it's not running it through RVM. We have a couple other capistrano plugins (e.g. `capistrano-puma`, `capistrano-sidekiq`) that work similarly but do run through RVM (see green arrows below). For example:

![image](https://user-images.githubusercontent.com/651946/50643797-a9067700-0f34-11e9-99ec-46d0a625781e.png)

I'm currently digging into the source code for this gem and other capistrano gems to see if I can't figure it out myself, but I thought I'd mention it in case you can provide any insight.

# Details
* `ruby`: 2.4.4
* `rails`: 5.2.2
* `capistrano`: 3.11.0
* `capistrano-rpush`: 0.2.0
* `capistrano-rails`: 1.4.0
* `capistrano-rvm`: 0.1.2

**Comment by melriffe** [comment]
@codebycliff Thank you for the detailed issue submission. At this time I'm not able to follow-up, properly, but wanted to let you know that I have received this.

**Comment by melriffe** [comment]
@codebycliff First, I appreciate your patience with my issues. Second, I added you as a collaborator to this project. Third, I released a new version of the gem because I decided to take the bull by the horns, as it were. It'd been a long time since I released a version and I was a little bit nervous. However, what made it easy was your straightforward pull request (because I hadn't had to deal with one until yours). Fourth, I added you as an author of the gem and put your email address in the gemspec.

Thanks for being both patient and insistent. 👍
